Repository harshmittal1750/Hacktoberfest-imagine-your-contribution, pull requests merged in 2021-10, with the labels that each got.

#22 Tower of Hanoi in c++
  C and CPP programs/Bit_Strings.cpp
  C and CPP programs/Coin_Piles.cpp
  C and CPP programs/Tower_of_Hanoi.cpp
  C and CPP programs/Trailing_Zeros.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#24 added the radix sort data structure
  C and CPP programs/Radix_sort.c
Labels: hacktoberfest-accepted, hacktoberfest

#23 added new features into readme
  CONTRIBUTOR.md
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#25 Create gcd.cpp
  C and CPP programs/gcd.cpp
  C and CPP programs/lcm.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#26 Recursive_Binary_Search
  Python programs/Binary_Search_Recursive.py
Labels: hacktoberfest-accepted, hacktoberfest

#27 added few data structures implemented in c++
  C and CPP programs/data structures/binarysearch.cpp
  C and CPP programs/data structures/bubblesort.cpp
  C and CPP programs/data structures/linearsearch.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#28 CSES Problems
  C and CPP programs/Increasing_Array.cpp
  C and CPP programs/Permutations.cpp
  C and CPP programs/Two_Sets.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#29 Bank_management_system in python
  Python programs/Bank_management.py
Labels: hacktoberfest-accepted, hacktoberfest

#31 Create break_a_palindrome.cpp
  C and CPP programs/break_a_palindrome.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#32 Create combination_sum.cpp
  C and CPP programs/combination_sum.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#33 Create remove_duplicates.py
  Python programs/remove_duplicates.py
Labels: hacktoberfest-accepted, hacktoberfest

#37 B_Equidistant_String.cpp
  C and CPP programs/B_Equidistant_String.cpp
  C_Omkar_and_Waterslide.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#36 Create permutations.cpp
  C and CPP programs/permutations.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#35 Contact us form
  html and css/Contact us form abhishek213-alb/img/bg.jpg
  html and css/Contact us form abhishek213-alb/img/work-g57e766a64_1280.png
  html and css/Contact us form abhishek213-alb/index.html
  html and css/Contact us form abhishek213-alb/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#34 Created InsertionSort.cpp in Data Structure
  C and CPP programs/data structures/InsertionSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#38 added heap sort.cpp
  C and CPP programs/data structures/heapsort.cpp
  C and CPP programs/permutations.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#39 added fibonacci.py
  Python programs/fibonacci.py
Labels: hacktoberfest-accepted, hacktoberfest

#42 Animated Watch using HTML and CSS
  html and css/Animated_Watch/index.html
  html and css/Animated_Watch/styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#41 Point_Meeting.cpp
  C and CPP programs/2_D_Point_Meeting.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#40 added binarytodecimal.cpp
  C and CPP programs/binarytodecimal.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#43 Add files via upload
  Python programs/Find the intersection of 2 arrays.py
Labels: hacktoberfest-accepted, hacktoberfest

#48 created code for reversing linked list
  C and CPP programs/data structures/reverseLinkedList.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#47 wirte your name in star patterns
  Python programs/nameinstarts.py
Labels: hacktoberfest-accepted, hacktoberfest

#46 Add files via upload
  C and CPP programs/Merge_2_sorted_arrays_without_using_extra_space.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#44 Add files via upload
  C and CPP programs/A_Add_Candies.cpp
  C and CPP programs/A_Buy_the_String.cpp
  C and CPP programs/A_Casimir_s_String_Solitaire.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#53 Add files via upload
  Python programs/Hangman.py
Labels: hacktoberfest-accepted, hacktoberfest

#52 Create guess.c
  C and CPP programs/Number guessing Game/guess.c
Labels: hacktoberfest-accepted, hacktoberfest

#51 Add A NODE TO LINKED LIST
  C and CPP programs/LinkedList_AppendNode.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#50 Add files via upload
  C and CPP programs/A_Puzzle_From_the_Future.cpp
  C and CPP programs/Alice_vs_Bob_Faceoff.cpp
  C and CPP programs/C_A_Cookie_for_You.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#49 Fault_Cal
  Python programs/Fault_cal.py
Labels: hacktoberfest-accepted, hacktoberfest

#55 Create Binary_Search_Iterative.py
  Python programs/Binary_Search_Iterative.py
Labels: hacktoberfest-accepted, hacktoberfest

#60 palindrome Numbers
  Python programs/PalindromeNumbers.py
Labels: hacktoberfest-accepted, hacktoberfest

#57 Add files via upload
  C and CPP programs/A New Technique.cpp
  C and CPP programs/A. Finding Sasuke.cpp
  C and CPP programs/A. Marketing Scheme.cpp
  C and CPP programs/C. Chef Monocarp.cpp
  C and CPP programs/C. Increase and Copy codeforces.cpp
  C and CPP programs/C. Longest Regular Bracket Sequence.cpp
  C and CPP programs/FOXLINGS soh.cpp
  C and CPP programs/FRNDCIRC spoj.cpp
  C and CPP programs/Help Diyvanshu.cpp
  C and CPP programs/LOSTNSURVIVED  spoj.cpp
  C and CPP programs/LOWEST COMMON ANCESTOR AND MINIMUM DISTANCE - BINARY LIFTING.cpp
  C and CPP programs/Lowest CommonAncestor graph.cpp
  C and CPP programs/The Circular jump (Lowe) hackerearth.cpp
  C and CPP programs/The Hard Work of Paparazzi.cpp
  C and CPP programs/The Witches of HEgwarts! hackereartg.cpp
  cororna.cpp
  counting rooms CSES.cpp
  covid19b codechef.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#56 Add files via upload
  Python programs/WhatsappBomber.py
Labels: hacktoberfest-accepted, hacktoberfest

#62 drop down menus using html,css.
  html and css/01-spinner-simples/index.html
  html and css/01-spinner-simples/spinner.css
  html and css/01-spinner-simples/style.css
  html and css/02-spinner-loader/index.html
  html and css/02-spinner-loader/spinner.css
  html and css/02-spinner-loader/style.css
  html and css/03-calculadora/index.html
  html and css/03-calculadora/style.css
  html and css/dropdown-menu/background.jpg
  html and css/dropdown-menu/dropdown-menu.css
  html and css/dropdown-menu/index.html
  html and css/dropdown-menu/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#63 Add files via upload
  C and CPP programs/Nice Matrix codeforces.cpp
  C and CPP programs/Odd-Even Subarrays.cpp
  C and CPP programs/owl fight hackerearth.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#64 Create QuickSort.cpp
  C and CPP programs/data structures/QuickSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#67 Create BubbleSort.c
  C and CPP programs/BubbleSort.c
Labels: hacktoberfest-accepted, hacktoberfest

#65 Customers Page
  html and css/customers page.html
Labels: hacktoberfest-accepted, hacktoberfest

#66 Create JadenCase.py
  Python programs/JadenCase.py
Labels: hacktoberfest-accepted, hacktoberfest

#70 Add files via upload
  1000folder.py
Labels: hacktoberfest-accepted, hacktoberfest

#69 Add files via upload
  Python programs/Turtule Race.py
Labels: hacktoberfest-accepted, hacktoberfest

#68 Create Largest_item_in_binary_tree.c
  C and CPP programs/Largest_item_in_binary_tree.c
Labels: hacktoberfest-accepted, hacktoberfest

#72 Problem Added - Maximum Product Subarray
  C and CPP programs/Maximum_Product_Subarray.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#73 Added maximum perimeter triangle solution
  Python programs/maximum_perimeter_triangle.py
Labels: hacktoberfest-accepted, hacktoberfest

#75 my contribution :)
  C and CPP programs/FakeGCD.cpp
  Python programs/FAKESWAP.py
Labels: hacktoberfest-accepted, hacktoberfest

#74 Add files via upload
  simple pattern.py
Labels: hacktoberfest-accepted, hacktoberfest

#82 Python program to illustrate Caesar Cipher Technique.
  Python programs/CaesarCipher-Encryption.py
Labels: hacktoberfest-accepted, hacktoberfest

#81 Added dfs.cpp
  C and CPP programs/dfs.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#80 Create scientific_calculator.py
  Python programs/scientific_calculator.py
Labels: hacktoberfest-accepted, hacktoberfest

#79 Create jump_game.cpp
  jump_game.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#78 Add files via upload
  Python programs/twisted fibonacci.py
Labels: hacktoberfest-accepted, hacktoberfest

#77 Fixes #76 (Repository Hits (or visitor) counter in readme.md file)
  README.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#84 Create countdown-timer.py
  Python programs/countdown-timer.py
Labels: hacktoberfest-accepted, hacktoberfest

#83 Added QRCode_generator.py
  Python programs/QRCode_generator.py
Labels: hacktoberfest-accepted, hacktoberfest

#85 Added bfs.cpp
  C and CPP programs/bfs.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#86 Create Tic_Tac_Toe.py
  Python programs/Tic_Tac_Toe.py
Labels: hacktoberfest-accepted, hacktoberfest

#88 Top 50 Spotify Songs-(EDA and PREPROCESSING)
  Python programs/Top 50 Spotify Songs.ipynb
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#87 added new project in HTML & CSS
  html and css/Animation Clock/README.md
  html and css/Animation Clock/clock image.png
  html and css/Animation Clock/clock.html
  html and css/Animation Clock/style.css
  html and css/Animation Clock/wall.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#91 added changes in readme
  Python programs/tic_tac_toe.py
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#94 Create TravellingSalesman.py
  Python programs/TravellingSalesman.py
Labels: hacktoberfest-accepted, hacktoberfest

#93 Count sort of string of alphabets
  C and CPP programs/Count_sort_string.cpp
Labels: hacktoberfest-accepted, hacktoberfest
